brew "curl"
brew "git"
brew "mas"
brew "mole"
brew "thefuck"
brew "tlrc"
brew "tree"
brew "vim"
brew "wget"
brew "zsh"
cask "1password"
cask "adobe-acrobat-reader"
cask "alfred"
cask "font-edu-nsw-act-foundation"
cask "font-edu-sa-beginner"
cask "font-montserrat"
cask "font-playwrite-au-sa"
cask "google-chrome"
cask "keyboardcleantool"
cask "logi-options+"
cask "microsoft-auto-update"
cask "microsoft-office"
cask "mos"
cask "numi"
cask "spotify"
cask "webex-meetings"
cask "whatsapp"
mas "Amphetamine", id: 937984704
mas "iMovie", id: 408981434
mas "Mela", id: 1568924476
